# Capstone Project - The Battle of Neighborhoods (Week 1)

### Table of Contents:
* Introduction: Business Problem
* List 2

### Introduction: Business Problem

In [21]:
import requests # library to handle requests
import pandas as pd
import numpy as np
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
from IPython.display import display_html
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium --yes
import folium # plotting library
from bs4 import BeautifulSoup
from sklearn.cluster import KMeans
import matplotlib.cm as cm
import matplotlib.colors as colors

print('Folium installed')
print('Libraries imported.')

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/ronald/opt/anaconda3

  added / updated specs:
    - folium


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    folium-0.12.0              |     pyhd8ed1ab_0          64 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          64 KB

The following packages will be UPDATED:

  folium                                         0.5.0-py_0 --> 0.12.0-pyhd8ed1ab_0



Downloading and Extracting Packages
folium-0.12.0        | 64 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Folium installed
Libraries imported.

In [22]:
df = pd.read_csv("DOH_COVID_Data_Drop_ 20210128_-_04_Case_Information.csv")

/Users/ronald/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [20]:
df.head()

,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
0,C783698,46.0,45 to 49,MALE,2020-07-30,2020-08-03,2020-08-05,NaN,NaN,RECOVERED,...,ISABELA,SAN PABLO,PH023133000,NaN,NaN,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."
1,C403584,NaN,NaN,MALE,2020-07-18,2020-07-19,2020-07-22,NaN,NaN,RECOVERED,...,NCR,NaN,NaN,NaN,NaN,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."
2,C186139,58.0,55 to 59,MALE,2020-08-20,2020-08-24,2020-08-26,NaN,NaN,RECOVERED,...,NCR,QUEZON CITY,PH137404000,NaN,NaN,RECOVERED,NO,2020-08-20,NaN,"Removal Type is ""Recovered"", but no Recovered ..."
3,C746546,26.0,25 to 29,MALE,2020-12-28,2020-12-28,2020-12-31,NaN,NaN,RECOVERED,...,NaN,NaN,NaN,NaN,NaN,RECOVERED,NO,NaN,NaN,"Removal Type is ""Recovered"", but no Recovered ..."
4,C223498,52.0,50 to 54,FEMALE,NaN,2020-04-15,2020-04-18,NaN,NaN,RECOVERED,...,NaN,NaN,NaN,NaN,NaN,RECOVERED,NO,NaN,NO,"Health Status is ""Recovered"", but no Date Reco..."